; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Pdc"
#define MyAppVersion "2.4.0.7"
#define MyAppPublisher "Pdc Team"
#define MyAppURL "http://privacydatacoin.com"
#define MyAppExeName "Pdc.exe"

[Setup]
AppId={{65FD6D06-3A2D-47FB-AA45-2B302C1C9D9E}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={pf32}\{#MyAppName}
DefaultGroupName={#MyAppName}
OutputBaseFilename=setup
Compression=lzma
SolidCompression=yes
ChangesAssociations=yes
ArchitecturesInstallIn64BitMode=x64
WizardImageFile=../../../../resources/installer_bg_164x313.bmp
;WizardSmallImageFile=../../../../resources/icon.bmp
PrivilegesRequired=poweruser
ArchitecturesAllowed=x64
;SetupIconFile=../../../../resources/app.ico
AppMutex=Pdc_instance
UninstallDisplayIcon={app}\{#MyAppExeName}


[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "desktopicon\common"; Description: "For all users"; GroupDescription: "{cm:AdditionalIcons}"; Flags: exclusive
Name: "desktopicon\user"; Description: "For the current user only"; GroupDescription: "{cm:AdditionalIcons}";  Flags: exclusive unchecked


[Registry]
Root: HKCR; Subkey: ".dbl"; ValueType: string; ValueName: ""; ValueData: "PdcWalletDataFile"; Flags: uninsdeletevalue
Root: HKCR; Subkey: "PdcWalletDataFile"; ValueType: string; ValueName: ""; ValueData: "Pdc Wallet's Data File"; Flags: uninsdeletekey
Root: HKCR; Subkey: "PdcWalletDataKyesFile"; ValueType: string; ValueName: ""; ValueData: "Pdc Wallet's Keys File"; Flags: uninsdeletekey

Root: HKCR; Subkey: "PdcWalletDataFile\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\Pdc.exe,0"
Root: HKCR; Subkey: "PdcWalletDataKyesFile\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\Pdc.exe,0"

Root: HKCR; Subkey: "Pdc"; ValueType: string; ValueName: "URL Protocol"; ValueData: ""
Root: HKCR; Subkey: "Pdc\shell\open\command"; ValueType: string; ValueName: ""; ValueData: "{app}\Pdc.exe --deeplink-params=%1"


[Files]

Source: "{#BinariesPath}\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs overwritereadonly
Source: "../../../../src/gui/qt-daemon/layout/html/*"; DestDir: "{app}\html"; Flags: ignoreversion recursesubdirs overwritereadonly
Source: "{#BinariesPath}\vc_redist.x86.exe"; DestDir: {tmp}; Flags: deleteafterinstall
Source: "..\..\..\..\resources\installer_bg_*.bmp"; Excludes: "*313.bmp"; Flags: dontcopy
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{group}\{cm:ProgramOnTheWeb,{#MyAppName}}"; Filename: "{#MyAppURL}"
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"
Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon\common
Name: "{userdesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon\user
